server:
  port: 9000

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MisterZP/Kratos.git
          search-paths: config-repository

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9100/eureka/
